### ISSUE TITLE
[Team3]팀원 정보 추가

### ISSUE THREAD

**Issue by bestday-ing** [openstack-kr/contributhon-2018-knu#41]
[Team3] 팀원 정보 추가

**Comment by joyfulgrace3** [comment]
허철훈 (abc7132@naver.com, fairy-of-9, 4)

    신정훈(ot2406@naver.com,post6393,4)

    이지언(dlwldjs7544@naver.com,JieonLee,1)

    조윤하(jyh66234359@gmail.com, yunhacho, 1)

**Comment by yongtaecheon** [comment]
정유빈 (yubina12@naver.com, bestday-ing, 3)

    천용태Cheon Yongtae(ide2143@naver.com,yongtaecheon,1)


    최성훈Choi-Sung-Hoon(tjdgns9246@naver.com, Choi-Sung-Hoon, 4)  << 

    송종영Son Jong Young(sondahum@gmail.com, suy427, 3)
