### ISSUE TITLE
[Team 2]팀원 정보 추가

### ISSUE THREAD

**Issue by donghoon-song** [openstack-kr/contributhon-2018-knu#42]
Team 2

    -윤서원 (floidea@naver.com, YunSeoWon, 3)

    -김동욱 (gygacpu@naver.com,Dong-wook94 , 3 )

    -구영준 (guyeongjun95@gmail.com, gaki2745, 2 )

    -손민주(alswn1531@naver.com, sonjminju, 2)

**Comment by ianychoi** [comment]
Closed thanks to https://github.com/openstack-kr/contributhon-2018-knu/pull/55
