### ISSUE TITLE
[Team 8] 팀원 정보 추가

### ISSUE THREAD

**Issue by ghost** [openstack-kr/contributhon-2018-knu#45]

**Comment by donghoon-song** [comment]
최연제 (dbdbdb156@naver.com, dbdbdb156,3) 

    송동훈 (thdehdgns@gmail.com, Donghoon759, 3) 

    조민국 (strike0115@naver.com,minkukjo,3)

    김상구 (kiy5214@naver.com, kimsanggoo, 2)

**Comment by dbdbdb156** [comment]
Team 8 정보 추가

팀원 : 송동훈,조민국,최연제,김상구
Co-authored-by: 최연제 (dbdbdb156@naver.com, dbdbdb156,3) 
Co-authored-by: 송동훈 (thdehdgns@gmail.com, Donghoon759, 3) 
Co-authored-by: 조민국 (strike0115@naver.com,minkukjo,3)
Co-authored-by: 김상구 (kiy5214@naver.com, kimsanggoo, 2)
Closes: #[45]
