### ISSUE TITLE
[TEAM 7] 팀원 정보 추가

### ISSUE THREAD

**Issue by LemonDouble** [openstack-kr/contributhon-2018-knu#48]
1. 조수현 ( [lemondouble](https://github.com/LemonDouble), 3 )
<suhyeon_cho@knu.ac.kr>
2. 김민석 ( [dheldh77](https://github.com/dheldh77), 3)
<dheldh77@icloud.com>
3. 이승우 ( [l4111kl](https://github.com/l4111kl),  2)
<leejiwon0516@gmail.com>
4. 김태원([Ktaewon](https://github.com/Ktaewon), 2)
<dydalehdxo@naver.com>

**Comment by ianychoi** [comment]
Closed thanks to https://github.com/openstack-kr/contributhon-2018-knu/pull/68
